#pragma once

#include <string>

namespace zcpm
{
// Commandline options that control how the emulation behaves
struct Config
{
    bool memcheck;                  // Are memory accesses checked? (Can be temporarily overridden at runtime)
    bool log_bdos;                  // Should calls to BDOS functions be logged?
    bool protect_warm_start_vector; // Protect against modification of the warm start vector?
    bool protect_bdos_jump;         // Protect against modification of the BDOS jump vector?
    std::string bdos_sym;           // Filename of BDOS symbols (generated by the assembler)
    std::string user_sym;           // Filename of symbols for a user executable (ditto)
};
} // namespace zcpm
